### ISSUE TITLE
After successful installation webview implementation is listed as "Android Webview"

### ISSUE THREAD

**Issue by fynks** [Magisk-Modules-Alt-Repo/open_webview#24]
First of all thanks for your work.
My question is after i install open Webview and choose the vanadium as option, it downloads and states that installation is successful. Upon reebot when i go to developer options and see my webview implementation it states "Android Webview" instead of vanadium webview.Is it by design so or other case?

Magisk module status'
![IMG_20231008_181054.jpg](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/75840152/529ada49-eb2d-43e4-a06d-03698ddaa8be)

Android Developer options webview implementation settings:
![IMG_20231008_181109.jpg](https://github.com/Magisk-Modules-Alt-Repo/open_webview/assets/75840152/3aa45b64-1fb6-48d2-866e-865e69f86a66)

**Comment by F3FFO** [comment]
> First of all thanks for your work. My question is after i install open Webview and choose the vanadium as option, it downloads and states that installation is successful. Upon reebot when i go to developer options and see my webview implementation it states "Android Webview" instead of vanadium webview.Is it by design so or other case?
> 
> Magisk module status' ![IMG_20231008_181054.jpg](https://user-images.githubusercontent.com/75840152/273450762-529ada49-eb2d-43e4-a06d-03698ddaa8be.jpg)
> 
> Android Developer options webview implementation settings: ![IMG_20231008_181109.jpg](https://user-images.githubusercontent.com/75840152/273450792-3aa45b64-1fb6-48d2-866e-865e69f86a66.jpg)

No, it is strange, you should see the webview you have choosen to install.

Can you provide me some info:
- Did you upgrade from a previous version or the first time you install the module?
- OS version
- ROM
- magisk version
- official magisk?
- do you have kernelSU?

**Comment by fynks** [comment]
- I installed it two times from scratch( uninstalling module,rebooting and then reinstalling module and webview) but got same results
- OS Android 12
- MIUI 14.0.3 (xiaomi.eu version)
- Magisk 26.3
- Yes official magisk
- No i don't have kernelSU

**Comment by alr86** [comment]
I have same issue and when I open every app that needs system webview, app got crashed with this crash report:
(I have installed thorium)
```
time: 1731267090009
msg: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.auth.login.LoginActivity}: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2606)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2600)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2668)
	at android.view.View.<init>(View.java:5496)
	at android.view.View.<init>(View.java:5637)
	at android.view.ViewGroup.<init>(ViewGroup.java:704)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:364)
	at android.webkit.WebView.<init>(WebView.java:346)
	at android.webkit.WebView.<init>(WebView.java:333)
	at android.webkit.WebView.<init>(WebView.java:323)
	at org.microg.gms.auth.login.LoginActivity.createWebView(LoginActivity.java:204)
	at org.microg.gms.auth.login.LoginActivity.onCreate(LoginActivity.java:115)
	at android.app.Activity.performCreate(Activity.java:8639)
	at android.app.Activity.performCreate(Activity.java:8617)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3784)
	... 12 more
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
	... 30 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:480)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	... 31 more
```

**Comment by BugReportI** [comment]
I also encountered this problem.
This screenshot shows it is a success:

![Screenshot_20241217-143358_Trebuchet](https://github.com/user-attachments/assets/837db87f-e341-41f1-835a-6f73bd43ecc3)

But after rebooting and checking webview implementation in developer settings it shows this:

![Screenshot_20241217-143832_Trebuchet](https://github.com/user-attachments/assets/68422803-4e39-4b25-9557-b9ed096eb715)

1. Fresh install of module.
2. LineageOS 21 official
3. Latest canary Magisk
4. No KernelSU

**Comment by BugReportI** [comment]
I tried manually installing the Cromite webbiew and it gave this error:

![Screenshot_20241217-224954_Trebuchet](https://github.com/user-attachments/assets/554170e3-2efc-42cb-a616-5dfae1d1569a)

**Comment by F3FFO** [comment]
Like I said here https://github.com/Magisk-Modules-Alt-Repo/open_webview/issues/48 I cannot change the package name, anyway i will try to find a better way to install Cromite

**Comment by BugReportI** [comment]
> As it was said here: #48 this is not releated to my project, I cannot change the package name, anyway i will try to find a better way to install Cromite

I thought this module would handle changing the package name but I will probably have to wait until uazo changes it, to install cromite webview.
