### ISSUE TITLE
[BUG] I can not use any app with webview after install Thorium

### ISSUE THREAD

**Issue by alr86** [Magisk-Modules-Alt-Repo/open_webview#45]
When I open any app that needs system webview, app got crashed with this crash report:
```
time: 1731267090009
msg: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.auth.login.LoginActivity}: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:363)
	at android.webkit.WebView.getFactory(WebView.java:2606)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2600)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2668)
	at android.view.View.<init>(View.java:5496)
	at android.view.View.<init>(View.java:5637)
	at android.view.ViewGroup.<init>(ViewGroup.java:704)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:364)
	at android.webkit.WebView.<init>(WebView.java:346)
	at android.webkit.WebView.<init>(WebView.java:333)
	at android.webkit.WebView.<init>(WebView.java:323)
	at org.microg.gms.auth.login.LoginActivity.createWebView(LoginActivity.java:204)
	at org.microg.gms.auth.login.LoginActivity.onCreate(LoginActivity.java:115)
	at android.app.Activity.performCreate(Activity.java:8639)
	at android.app.Activity.performCreate(Activity.java:8617)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3784)
	... 12 more
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:532)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:348)
	... 30 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: android.content.pm.PackageManager$NameNotFoundException: Application package com.android.webview not found
	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:480)
	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:493)
	... 31 more
```

**Comment by F3FFO** [comment]
I'm sorry but Thorium webview was not stable and has been removed in the new version
